

```{r load-packages,error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(skimr)
library(tidymodels)
library(schrute)
library(lubridate)
```

```{r setup, error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
opts_chunk$set(echo=FALSE) # hide source code in the document
```

```{r risk, error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
library(haven)
### place the data in a "data" folder, stored with this .rmd file.
child_risk <- read_sav("./data/child_risk.sav")

```
```{r , error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
### cleaning data:
clean_data <- child_risk %>%
  dplyr::select(T3gender,ParentMeet:Hacha6, Hacha8:Hacha13, RakazBugrim:V28.5a, V28.1b:V28.5b,
HelpSeekInten1:HelpSeekInten4, T3_skills1:V35.9, V37, V38.8:V38.12,
life_skills_allT1:M1.4, B.STUDY.NOW:B.EDUCATION, B.CONTACT:B.LIFE.SKILLS.ALL_9,
B.FUTURE.EXPECT.ALL_4:B.FUTURE.EXPECT.ALL_9, B.MAIN.OCCUPATION:B.MAIN.OCCUPATION_7,
Support:B_life_skills_housing, B_main_occupation_duty, B_contact_frequency,
B_rakaz_support, ActSeekRightsT2, ActSeekCareerT2, T3education_1:T3education_courses,
T3allowence:T3job_no, T314.10:T3staffRakaz_evalua, T3_10.20:T3_10.155,
T3_15.230_1:T3_15.230_5, T3_21.140_1:T3_21.140_6, -B.MAINOCCUPATION.TEXT,
-T3allowence_1_TEXT, -T3chronic_disability_1_TEXT, -T3_welfare_service_1_12_TEXT,
-T3_welfare_service_2_12_TEXT, -T3Rakaz_1_3_TEXT, -T3place_staff_yozm_3_TEXT,
-B.HELP.COVID, -B.HELP.COVID.DEGREE, -B.HELP.COVID.TEXT, -B.MAIN.OCCUPATION.TEXT,
-B.STUDY.COVID_text, -B.STUDY.TEXT, -FormalM3)%>%
  mutate(T3_welfare_service_1_1_1 = ifelse(is.na(T3_welfare_service_1_1_1), 0,
T3_welfare_service_1_1_1))%>%
  drop_na(T314.10)
```

```{r , error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
### cleaning data:
replace_na_with_zero <- function(x) {
  replace(x, is.na(x), 0)
}
replace_1_with_0_and_2_with_1 <- function(x) {
  replace(x, x %in% c(1, 2), c(0, 1))
}

# Replace NA values with 0 for variables v1, v2, and v3 using the function
clean_data <- clean_data %>%
  mutate(across(T3place_staff_1:T3place_staff_5, replace_na_with_zero))%>%
  mutate(across(B.HELP.EDUC:B.HELP.NONPROFIT.DEGREE, replace_na_with_zero))%>%
  mutate(across(T3_welfare_service_1_1_1:T3_welfare_service_2_12, replace_na_with_zero))%>%
  mutate(across(T3Adverse_Events_1:T3_ACE_9, replace_1_with_0_and_2_with_1))%>%
  mutate(across(T3education_courses:T3allowence, replace_1_with_0_and_2_with_1))%>%
  mutate(across(T3staffandRakaz_help_1_1:T3staffandRakaz_help_1_9, replace_1_with_0_and_2_with_1))
```

```{r , echo=FALSE, error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
clean_data <- clean_data %>%
  dplyr::select(-T3job_no, -T3_job)%>% 
   rename(income_level = T314.10)

```

```{r , echo=FALSE, error=FALSE, include=FALSE, message = FALSE, warning=FALSE}
library(ggcorrplot)
library(caret)
library(randomForest)
library(gam)

excluded_column <- c(136,179,189, 200, 207, 209)
column_range <- setdiff(1:279, excluded_column) # excluding the outcome feature

```

```{r , echo=FALSE, error=FALSE, warning=FALSE}
library(haven)
library(recipes)

clean_data <- clean_data%>%
  mutate(income_level = case_when(income_level==1 ~ 0, income_level==2 ~ 2000, income_level==3 ~ 3000,
income_level==4 ~ 4000, income_level==5 ~ 5000,
income_level==6 ~ 6000, income_level==7 ~ 7500,
income_level==8 ~ 10000, income_level==9 ~ 14000,
income_level==10 ~ 21000, income_level==11 ~ 0))
# using feature importance
roc_imp <- filterVarImp(x = clean_data[,column_range], y = clean_data$income_level)
roc_imp <- data.frame(cbind(variable = rownames(roc_imp), score = roc_imp[,1]))
roc_imp$score <- as.double(roc_imp$score)
roc_imp<-roc_imp[order(roc_imp$score,decreasing = TRUE),]

### only selecting out of the 50 most important variables:
variable_values <- roc_imp$variable
values <- head(variable_values, 50)

### removing the least significant variables to our model: 
important_features <- clean_data%>%
  dplyr::select(values,income_level, -B.LIFE.SKILLS.ALL_4, -T3education_courses, -T3_ACE_8, -T3_ACE_9,
-T3_15.230_2, -T3_welfare_service_2_4, -T3_welfare_service_2_9,
-Hacha9, -V35.8, -T3_15.230_1, -T3place_staff_freq, -T3staffandRakaz_help_2_3,
-HelpSeekInten2, -B.CONTACT.INITIATE, -B.HELP.EDUC, -T3_10.150, -T3_SRH, -T3_10.150.1,
-B.FUTURE.EXPECT.ALL_6, -Hacha2, -B.LIFE.SKILLS.ALL_7, -T3_welfare_service_2_7,
-B.STUDY.COVID)%>% 
  mutate(across(everything(), as.numeric))%>%
  mutate_all(~ replace_na(., median(., na.rm = TRUE)))

set.seed(1116)
# Put 80% of the data into the training set 
youth_split <- initial_split(important_features, prop = 0.80)
# Create data frames for the two sets:
train_data <- training(youth_split)
test_data  <- testing(youth_split)
```

```{r , echo=FALSE, error=FALSE, warning=FALSE}
# Building recipe
youth_rec <- recipe(
 income_level ~ ., # formula
 data = train_data # data to use for cataloguing names and types of variables
 )
# Define model
youth_mod <- linear_reg() %>%
  set_engine("lm")
# Define workflow
youth_wflow <- workflow() %>%
 add_model(youth_mod) %>%
 add_recipe(youth_rec)
# Fit model to training data
youth_fit <- youth_wflow %>%
 fit(data = train_data)
```

```{r , echo=FALSE, error=FALSE, warning=FALSE}

linear_model_results <- youth_fit%>% tidy()%>% 
  filter(term != "(Intercept)") %>% 
  arrange(desc(estimate))

```


```{r sqr}
glance(youth_fit)$r.squared  # R-squared
```


```{r adj}
glance(youth_fit)$adj.r.squared # Adjusted R-squared
```


```{r }
train_pred <- predict(youth_fit, train_data) %>%
 bind_cols(train_data %>% dplyr::select(income_level))%>%
  mutate(.pred = ifelse(.pred < 0, 0, .pred))

# Calculate the mean squared error (MSE)
train_rmse <- RMSE(train_pred$income_level, train_pred$.pred)

test_pred <- predict(youth_fit, test_data) %>%
 bind_cols(test_data %>% dplyr::select(income_level))%>%
  mutate(.pred = ifelse(.pred < 0, 0, .pred))


# Calculate the mean squared error (MSE)
test_rmse <- RMSE(test_pred$income_level, test_pred$.pred)

cat("RMSE score:", test_rmse, "\n")
```


```{r}
# Set the seed
set.seed(1116)

# Create a vfold cross-validation object
youth_vfold <- vfold_cv(train_data, v = 10)  # Specify the number of folds you want to use

# Define the updated workflow
youth_wflow <- workflow() %>%
  add_model(youth_mod) %>%
  add_recipe(youth_rec)

# Fit and evaluate the model using cross-validation
youth_fit_cv <- youth_wflow %>%
  fit_resamples(resamples = youth_vfold)
# Get the summary statistics for R-squared and adjusted R-squared
collect_metrics(youth_fit_cv)

```


```{r, echo=FALSE, out.width="50%", out.height="50%", warning=FALSE}
# Extract the coefficients from the fitted model
coefficients <- tidy(youth_fit)[-1, ]

# Sort the coefficients based on their absolute values
sorted_coeffs <- coefficients[order(coefficients$estimate, decreasing = TRUE), ]

# Select the top 5 predictors with the largest positive impact
top_positive_predictors <- head(sorted_coeffs, 5)
# Select the top 5 predictors with the largest negative impact
top_negative_predictors <- tail(sorted_coeffs, 5)

# Combine the positive and negative predictors
top_predictors <- rbind(top_positive_predictors, top_negative_predictors)

top_predictors$term <- factor(top_predictors$term,
levels = top_predictors$term[order(-top_predictors$estimate)])

# Define new labels for the predictors
new_labels <- c("Ethnical Discrimination" = "T3_21.140_2",
                "Looking for Job" = "T3job_seeking",
                "Probation Officer at Youth" = "T3_welfare_service_1_9_2",
                "Having an Apartment in Future" = "B.FUTURE.EXPECT.ALL_5",
                "Having a Mentor" = "Mentor",
                "Contact with Alumni Coordinator" = "B.CONTACT.WHO_rakaz",
                "Family Treatment at Youth" = "T3_welfare_service_1_3_2",
                "Contact Frequency with Village Staff" = "B_contact_frequency",
                "Yated Social Worker Help Level" = "T3_welfare_service_2_11",
                "Other Welfare Services at Youth" = "T3_welfare_service_1_12_2")

# Recode the labels of the predictors
top_predictors <- top_predictors %>%
  mutate(term = fct_recode(term, !!!new_labels))

# Create a bar plot of the top 10 predictors
ggplot(top_predictors, aes(x = estimate, y = term,
fill = ifelse(estimate >= 0, "Positive", "Negative"))) +
  geom_bar(stat = "identity", color = "white") +
  labs(x = "Coefficient Estimate", y = "Predictors",
       title = "Most Impactful Predictors by Coefficient Estimate",
 subtitle = "Linear regression predictors fitted to training data",
 caption = "Data: Trajectories of at-risk youth (longitudinal data), by Dr. Talia Schwartz-Tayri ") +
  scale_fill_manual(values = c("#ef3b2c", "#74c476"), guide = FALSE) +
  theme_minimal()
```

```{r , echo=FALSE, error=FALSE, message = FALSE, warning=FALSE}
library(haven)
library(recipes)
### only selecting out of the 50 most important variables:


### removing the least significant variables to our model: 
regularized_data <- clean_data%>%
  mutate(across(everything(), as.numeric))%>%
  mutate_all(~ replace_na(., median(., na.rm = TRUE)))%>% 
  mutate(income_level = factor(income_level))

```

```{r modify, echo=FALSE, error=FALSE, warning=FALSE, include=FALSE}
regularized_data <- regularized_data %>% 
  mutate(income_level = fct_recode(income_level,
                            "0" = "1",
                            "2000" = "2",
                            "3000" = "3",
                            "4000" = "4",
                            "5000" = "5",
                            "6000" = "6",
                            "7500" = "7",
                            "10000" = "8",
                            "14000" = "9",
                            "21000" = "10",
                            "0" = "11"))


set.seed(1116)
# Put 80% of the data into the training set 
youth_split <- initial_split(regularized_data, prop = 0.80)
# Create data frames for the two sets:
train_data_ord_fct <- training(youth_split)
test_data_ord_fct <- testing(youth_split)

```


```{r, echo=FALSE, error=FALSE, warning=FALSE, include=FALSE}
set.seed(1116)
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(caret)


# Define the control parameters for the random forest model
ctrl <- trainControl(method = "cv",   # Cross-validation
                     number = 10,      # Number of folds
                     verboseIter = FALSE)  # Display progress

# Train the random forest model using the train() function
model <- train(income_level ~ .,              # Formula specifying dependent variable and predictors
               data = train_data_ord_fct,       # Training data
               method = "rf",                 # Random forest method
               trControl = ctrl,              # Control parameters
               tuneLength=25)               

# Print the model results
print(model)
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, include=FALSE}
# Calculate variable importance
importance <- varImp(model)

# Get the top 30 predictors
top30_indices <- order(importance$importance[, "Overall"], decreasing = TRUE)[1:30]
top30_predictor_names <- rownames(importance$importance)[top30_indices]

selected_columns_subset_fct <- train_data_ord_fct[, c(top30_predictor_names, "income_level")]

require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)

m <- polr(income_level ~ ., data = selected_columns_subset_fct, Hess=TRUE , method = "probit")
summary(m)

ctable <- coef(summary(m))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
predicted <- predict(m, newdata = test_data_ord_fct, type = "class")

actual <- test_data_ord_fct$income_level

```


```{r, echo=FALSE, out.width="50%", out.height="50%", warning=FALSE}
predicted <- as.numeric(as.character(predicted))
# Convert income_level to numeric
actual <- as.numeric(as.character(actual))

df <- data.frame(Actual = actual, Predicted = predicted)

# Calculate RMSE
rmse=sqrt(mean((df$Actual - df$Predicted)^2))
rmse
```


```{r, out.width="50%", out.height="50%"}
# Extract coefficient names and values
ordinal_df <- data.frame(Coefficient = rownames(ctable),
                         Value = ctable[, "Value"])

# Select the first 30 rows, removing outliers:

# Sort the coefficients in descending order, removing outliers
sorted_coeffs <- ordinal_df[order(ordinal_df$Value, decreasing = TRUE), ]
sorted_coeffs<- sorted_coeffs[1:29, ]
# Select the top 5 predictors with the largest positive impact
top_positive_predictors <- head(sorted_coeffs, 5)

# Select the top 5 predictors with the largest negative impact
top_negative_predictors <- tail(sorted_coeffs, 5)

# Combine the positive and negative predictors
top_predictors <- rbind(top_positive_predictors, top_negative_predictors)

# Define factor levels based on the order of the predictors
top_predictors$Coefficient <- factor(top_predictors$Coefficient,
levels = top_predictors$Coefficient[order(-top_predictors$Value)])

# Define new labels for the predictors (if desired)
new_labels <- c("Satisfication with Level of Functioning" = "B.MAIN.OCCUPATION_4",
                "Readiness Index for Independent Living-Housing" = "M1.4",
                "Life Skills Index-Self living" = "B_life_skills_housing",
                "Having an Apartment in Future" = "B.FUTURE.EXPECT.ALL_5",
                "Trust Level in Village's Staff" = "PnimiaTrust",
                "Rakaz's Help-Military/National Service" = "V28.2b",
                "Feeling Nervous" = "T3_10.150",
                "Studying since High-School" = "T3education_1",
                "Life Skills Index-Before Leaving the Vilage" = "life_skills_allT1",
                "Functioning in Main Occopation Index" = "B_main_occupation_duty")

# Recode the labels of the predictors
top_predictors$Coefficient <- fct_recode(top_predictors$Coefficient, !!!new_labels)

# Create a bar plot of the top predictors
ggplot(top_predictors, aes(x = Value, y = Coefficient,
fill = ifelse(Value >= 0, "Positive", "Negative"), cex.main = 0.8)) +
  geom_bar(stat = "identity", color = "white") +
  labs(x = "Coefficient Estimate", y = "Predictors",
       title = "Most Impactful Predictors by Coefficient Estimate",
 subtitle = "Ordinal regression predictors fitted to training data",
 caption = "Data: Trajectories of at-risk youth (longitudinal data), by Dr. Talia Schwartz-Tayri ") +
  scale_fill_manual(values = c("#ef3b2c", "#74c476"), guide = FALSE) +
  theme_minimal()+
  theme(plot.title = element_text(hjust =1),
        plot.subtitle = element_text(hjust = -1.5))
```



```{r}
# 50 most important feature and their scores, by the feature importance algorithm:
head(roc_imp, 50)
```


```{r}
# The linear model fit results:
linear_model_results
```


```{r}
# 30 most important feature and their scores, by regularization algorithm:
df <- data.frame(Predictor = top30_predictor_names,
Importance = importance$importance[top30_indices, "Overall"])
df
```


```{r}
#  The ordinal model fit results:
ctable
```

